- name: restart v2ray
  systemd:
    daemon_reload: true
    enabled: true
    name: v2ray
    state: restarted

- name: restart cron
  systemd:
    name: cron
    state: restarted

- name: flush iptables
  shell: flush-iptables.sh

- name: update dnsmasq-china-list
  shell: dnsmasq-china-list.sh
