- hosts: all
  vars_files:
    - defaults/basic.yml
    - defaults/advanced.yml
    - defaults/raw.yml

  tasks:
    - import_tasks: tasks/preflight.yml
    - import_tasks: tasks/v2ray_preflight.yml
    - import_tasks: tasks/v2ray_install.yml
    - import_tasks: tasks/v2ray_resources.yml
    - import_tasks: tasks/v2ray_configure.yml
    - import_tasks: tasks/iptables.yml
    - import_tasks: tasks/dnsmasq.yml
    - import_tasks: tasks/landing.yml

  handlers:
    - import_tasks: handlers/main.yml
