- hosts: all
  remote_user: root
  vars_files:
    - defaults/basic.yml
    - defaults/advanced.yml
    - defaults/extensions.yml
    - defaults/rules.yml
    - defaults/raw.yml
  vars:
    ansible_python_interpreter: python3

  tasks:
    - import_tasks: tasks/preflight.yml
    - import_tasks: tasks/v2ray_preflight.yml
    - import_tasks: tasks/v2ray_install.yml
    - import_tasks: tasks/v2ray_configure.yml
    - import_tasks: tasks/iptables.yml
    - import_tasks: tasks/dnsmasq.yml
    - import_tasks: tasks/healthcheck.yml
    - import_tasks: tasks/frpc.yml
      when: frpc_version != ''

  handlers:
    - name: restart v2ray
      systemd:
        daemon_reload: true
        enabled: true
        name: v2ray
        state: restarted

    - name: restart frpc
      systemd:
        daemon_reload: true
        enabled: true
        name: frpc
        state: restarted

    - name: restart cron
      systemd:
        name: cron
        state: restarted

    - name: flush iptables
      shell: flush-iptables.sh

    - name: update dnsmasq-china-list
      shell: dnsmasq-china-list.sh
