- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Generate dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644

- name: Generate dnsmasq-china-list installation script
  template:
    src: dnsmasq-china-list.sh.j2
    dest: &dnsmasq_china_list /usr/local/bin/dnsmasq-china-list.sh
    mode: 0755
  notify:
    - update dnsmasq-china-list

- name: Update dnsmasq-china-list on schedule
  cron:
    name: dnsmasq-china-list
    job: *dnsmasq_china_list
    special_time: weekly

- name: Copy dhcp leases helper script
  copy:
    src: files/dhcp-leases.sh
    dest: /usr/local/bin/
    mode: 0755
  when: dhcp_enabled | bool

- name: Restart dnsmasq service
  systemd:
    name: dnsmasq
    state: restarted
    enabled: true
