- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Generate dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644

- name: Restart dnsmasq service
  systemd:
    name: dnsmasq
    state: restarted
    enabled: true
