- import_tasks: tasks/preflight.yml
- import_tasks: tasks/domain_based_routing.yml
  when: domain_based_routing_enabled
- import_tasks: tasks/v2ray_preflight.yml
- import_tasks: tasks/v2ray_install.yml
- import_tasks: tasks/v2ray_resources.yml
- import_tasks: tasks/v2ray_configure.yml
- import_tasks: tasks/iptables.yml
- import_tasks: tasks/dnsmasq.yml
- import_tasks: tasks/landing.yml
