- name: Enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Disable all ipv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "{{ 1 if disable_all_ipv6 else 0 }}"
    sysctl_set: true
    state: present
    reload: true

- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  when: systemd_resolved == 'stopped'

- name: Set systemd-resolved mode
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  when: systemd_resolved == 'direct'
