- name: Print local network status
  debug:
    var: ansible_default_ipv4

- name: Set hostname
  hostname:
    name: "{{ kexue_hostname }}"
  when: kexue_hostname != ''

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai
  notify:
    - restart cron

- name: Replace APT repositories
  copy:
    src: files/apt-sources.list
    dest: /etc/apt/sources.list
    mode: 0644
    backup: true

- name: Install requirements
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - unzip
    - ipset
